name: dbt run

on:
  pull_request:
    branches:
      - main  # Spécifiez la branche cible des PRs
  push:
    branches:
      - 'feature/*'  # Pour chaque commit sur les branches de développement

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt
        run: |
          pip install dbt-bigquery  # ou autre adaptateur dbt

      - name: Build modified dbt models
        run: dbt build --select state:modified+
