name: dbt run

on:
  pull_request:
    branches:
      - main  # Spécifiez la branche cible des PRs
  push:
    branches:
      - 'feature/*'  # Pour chaque commit sur les branches de développement

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt
        run: |
          pip install dbt-bigquery

      - name: Set up Google Cloud Keyfile
        env:
          GCP_KEYFILE_JSON: ${{ secrets.GCP_KEYFILE_JSON }}
        run: |
          echo "$GCP_KEYFILE_JSON" > keyfile.json
          export GOOGLE_APPLICATION_CREDENTIALS=keyfile.json

      - name: Run dbt models
        env:
          DBT_PROJECT_ID: ${{ secrets.DBT_PROJECT_ID }}
        run: dbt build --select state:modified+
